export enum PopupChanelEnum {
  ADD_SEMESTER_TO_GROUP,
  CREATE_SEMESTER,
  CREATE_LESSONTIME,
  UPDATE_LESSONTIME,
  CREATE_GROUP,
  CREATE_COURSE,
  CREATE_SPECIALTY,
  CREATE_FACULTY,
  CREATE_UNIVERSITY,
  CREATE_HOUSING,
}
